### ISSUE TITLE
Graceful DDP Shutdown support

### ISSUE THREAD

**Issue by etyp** [zodern/mup-aws-beanstalk#32]
Hey - excellent package! This has been monumental in getting us fully onto AWS. We're moving off of Galaxy and a key benefit to using it was support for the [DDP Graceful Shutdown](https://github.com/meteor/ddp-graceful-shutdown/) package, which helps ease connections off of each Meteor container to avoid thrashing the CPU on new containers that the connections get routed to.

The package is pretty simple - it [listens for a `SIGTERM`](https://github.com/meteor/ddp-graceful-shutdown/blob/master/src/index.js#L27) and gradually kills each [websocket connection over a configurable grace period](https://github.com/meteor/ddp-graceful-shutdown/blob/master/src/index.js#L36).

Unfortunately, a `SIGTERM` isn't fired when Elastic Beanstalk begins draining connections. We've tried setting up an SNS topic attached to lifecycle hooks, subscribing to that, and running the `DDPGracefulShutdown.closeConnections` function but the solution is way too contrived.

Given you managed to build such an awesome plugin in record time, I figured you might have some ideas!

**Is there anything you can think of that requires minimal configuration that each container can listen on to drain connections?** I'd be happy to even pay a bounty on this one.

Thanks!

**Comment by etyp** [comment]
Also, happy to share the code we put together using SNS. In total it's about 100 LoC but I believe it hooks into the wrong lifecycle event so getting this working might just be a matter of exploring available lifecycle events.

**Comment by etyp** [comment]
@zodern if we pay (similar to how I think this whole project started), is there any way we could prioritize this?

**Comment by zodern** [comment]
I would like to add this feature. If you would be willing to sponsor it, that would be appreciated. I can try to make time for this next week.

**Comment by etyp** [comment]
Excellent. What's the best way to move forward with sponsoring it? Also we have a long thread with AWS support on their suggested implementation (plus code from our initial attempt) if that would be helpful.

Let me know about how we sponsor and we can move from there.

**Comment by zodern** [comment]
> Also we have a long thread with AWS support on their suggested implementation (plus code from our initial attempt) if that would be helpful.

That would be helpful.

> Let me know about how we sponsor and we can move from there.

I would like to discuss this over email. Could you send me an email to z-modern@live.com?

**Comment by etyp** [comment]
@zodern great, just emailed. Excited to get this underway!

**Comment by zodern** [comment]
I just released 0.6.0-beta1 which has this feature. You can try it by running `npm i -g mup-aws-beanstalk@next`. The documentation is available [here](https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/index.md#graceful-shutdown).

**Comment by etyp** [comment]
@zodern so we've finally got around to start testing this, thanks for all the work on it! We're running into an issue when trying to add the configuration to an existing environment and getting the following error on deploy:

```
=> Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
=> Ensuring Graceful Shutdown is setup
BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
    at Request.extractError (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:38:9)
```

Any idea what might be causing this?

**Comment by nab911** [comment]
Lastly, after working through it, we were getting permission issue around 
`AccessDeniedException: User: arn:aws:iam::409391052279:user/meteor-deploy-user is not authorized to perform: cloudtrail:DescribeTrails`

We gave both the roles used that permission and were still getting it. Full admin privileges got around it but we were wondering if you had a better idea of where the permission needs to be applied. Thanks!

**Comment by zodern** [comment]
> Has a hardcoded bucket name. Because AWS requires globally unique bucket names.

Thanks for identifying that. The plugin would only need to check if the bucket exists and create it when the cloud trail doesn't exist, so it should be fine to append it with something more random since it is shared between environments.

> We gave both the roles used that permission and were still getting it. Full admin privileges got around it but we were wondering if you had a better idea of where the permission needs to be applied. 

If you created a group as described in [step 3](https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/getting-started.md#step-3-create-aws-user) of the getting started guide, you can add the policies to it, or to the user created in that step.

**Comment by etyp** [comment]
@zodern it seems like even with the services listed in [step 3](https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/getting-started.md#step-3-create-aws-user), deployment fails with a message about `cloudTrail DescribeTrails`. Even after adding an inline policy with this to the deploy user, it still fails.

Also, re: the appending of something random, does mup need this bucket's name on each deployment? If so, how would a random value work?

Lastly, how easy is it to update the plugin to append `app.name`? We'd love to get this running in production but it's a blocker for us :)

**Comment by zodern** [comment]
> Also, re: the appending of something random, does mup need this bucket's name on each deployment? If so, how would a random value work?

The bucket name would look like `mup-graceful-shutdown-trail-<Date.now>-<a few random numbers>`. It already has a [list of the buckets](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/command-handlers.js#L82), so it can check if a bucket exists that starts with `mup-graceful-shutdown-trail` and use it. We should do the same thing with the other bucket this plugin creates so several users can have an environment with the same name.

> it seems like even with the services listed in step 3, deployment fails with a message about cloudTrail DescribeTrails. Even after adding an inline policy with this to the deploy user, it still fails.

To clarify, are these policies attached too? https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/index.md#graceful-shutdown

**Comment by zodern** [comment]
I published version `mup-aws-beanstalk@0.6.0-beta4` with the fix.

**Comment by etyp** [comment]
Ah did not see the graceful shutdown policies, thank you!

Re: bucket, single bucket works cross environments because the instance will only shutdown if it matches the cloudtrail event's instance id right? If so, then I think we're all set! 

We'll try this out and update you. Thanks!

**Comment by zodern** [comment]
> Re: bucket, single bucket works cross environments because the instance will only shutdown if it matches the cloudtrail event's instance id right? If so, then I think we're all set!

Yes, that is correct.

**Comment by etyp** [comment]
@zodern quick question --- [the docs for Graceful Shutdown](https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/index.md#graceful-shutdown) say to run `mup deploy` once the option is added.

Does `mup reconfig` work as well assuming the app bundle we have live is correct?

**Comment by zodern** [comment]
The bundle needs an additional file for graceful shutdown to work, which is only added during `mup deploy` when the option is enabled.

**Comment by zodern** [comment]
Starting in `0.6.0-beta6`,  it uses SSM Automation to run the commands only on the server being deregistered. This should fix problems in environments with a large number of servers.

To migrate to using SSM Automation, make sure your iam user has the [correct policies](https://github.com/zodern/mup-aws-beanstalk/blob/master/docs/index.md#graceful-shutdown) and run `mup setup` or `mup deploy`.

**Comment by etyp** [comment]
@zodern great news, the new SSM commands work for large batches! I think we can close this one out now :)
